[package]
name = "q3"
version = "0.1.0"
authors = ["alina <alinadotjavaid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
q3_lib={path="../q3_lib"}